### PR TITLE
Fixes #1 respect changed secret

### LINKED ISSUE #1: Changing Secret doesn´t have affect on already given access
1) set a secret for your site
2) access the site using the secret
3) change the secret
4) you still have access to the site

Access should be reset to all users after changing secret.

thanks,

Elisa

### PR DESCRIPTION
**Pull request by zero-24**
This should fix the secret problem.

To compare the current and the saved secret i have saved it now to the session and check it on every request. Maybe we should hash the secret before we save it to the session? I'm not sure.

### CODE REVIEW

**Comment by zero-24** [comment]
ahh found a problem I'm on it

**Comment by zero-24** [comment]
ok the problem should be fixed now. Feel free to test :smile: 

The only problem that remains is that if someone have a old value seven in the session you need to call the page two times at the first time you change the saved secret and at the seccond time you pass the checks

**Comment by brianteeman** [comment]
> The only problem that remains is that if someone have a old value seven in the session you need to call the page two times at the first time you change the saved secret and at the seccond time you pass the checks

Its not just if someone has the old value stored that this PR makes you have to do it twice
If you open a new browser that you have never used this on before and set the comingsoon word then it doesnt work the first time

**Comment by zero-24** [comment]
Yes i have missed something please test with the last change applyed it should do the trick :smile:

**Comment by brianteeman** [comment]
Thanks merged

**Pull request merged**
