### PR TITLE
:fr: proposal

### PR DESCRIPTION
**Pull request by MATsxm**
If you agree and merge it I will add the other .ini and edit the .xml

### CODE REVIEW

**Comment by brianteeman** [comment]
Knock yourself out - I will not however be adding this to crowdin etc

**Comment by MATsxm** [comment]
who's talking about Crowdin?

**Comment by brianteeman** [comment]
Just saying - if you or anyone else wants to submit translations here - then fine - but I am not going to set it up on any external translation service

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
